name: ToolTip
author: czukowski
category: Interface
tags: [Tooltip, Arrow]
sources: ['Source/ToolTip.js']
demo: http://czukowski.github.com/mootools-ToolTip/demo.html
docs: https://github.com/czukowski/mootools-ToolTip/blob/master/README.md